#!/bin/sh /etc/rc.common
#
# Copyright (C) 2014 JH de Wolff (jaap@de-wolff.org)
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

START=91
STOP=9
APP=open-giethoorn
PID_FILE=/var/run/$APP.pid

start() {
        start-stop-daemon -S -x $APP -p $PID_FILE -m -b
}

stop() {
        start-stop-daemon -K -n $APP -p $PID_FILE -s TERM
        rm -rf $PID_FILE
}
