#!/bin/sh /etc/rc.common
#
# Copyright (C) 2014 JH de Wolff 
#
# This file is a part of the open-giethoorn project 
#	http://github.com/de-wolff/OpenGiethoorn
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

START=91
STOP=9
APP=open-giethoorn
PID_FILE=/var/run/open-giethoorn.pid
. /usr/share/open-giethoorn/bin/vars

start() {
        start-stop-daemon -S -p $PID_FILE -m -b -x /usr/share/open-giethoorn/bin/run-service.sh
}

stop() {
        start-stop-daemon -K -n /usr/share/open-giethoorn/bin/run-service.sh -p $PID_FILE -s TERM
        rm -rf $PID_FILE
}
